### ISSUE TITLE
100% queries test coverage

### ISSUE THREAD

**Issue by wittydeveloper** [wittydeveloper/spotify-graphql#56]

**Comment by Jotakuun** [comment]
Hi @wittydeveloper 

I really want to contribute to this repo, so I may want to start helping with test coverage to get familiar with the code and maybe later I could contribute with some of the missing queries.

Are you open to accept these pull requests? 😄

**Comment by wittydeveloper** [comment]
Hi @Jotakuun !

Yes, I would love to have some help maintaining this project.
Feel free to open some pull requests, I'll reply as fast as I can (1-2 days)

Tell me if you have any questions on the code ;)
