### ISSUE TITLE
Cannot find resolvers

### ISSUE THREAD

**Issue by rshkv** [wittydeveloper/spotify-graphql#61]
Hi @wittydeveloper,

I'm trying to import `spotify-graphql` in a Typescript project, but I get the errors below during compilation. The import seems to come from `lib/resolvers.ts` and not `dist/lib/resolvers.js`. However, the `resolvers` folder is only in `dist/lib`, and not in just `lib`.

```
ERROR in [at-loader] ./node_modules/spotify-graphql/lib/resolvers.ts:1:32 
    TS2307: Cannot find module './resolvers/album'.

ERROR in [at-loader] ./node_modules/spotify-graphql/lib/resolvers.ts:2:33 
    TS2307: Cannot find module './resolvers/artist'.

ERROR in [at-loader] ./node_modules/spotify-graphql/lib/resolvers.ts:3:33 
    TS2307: Cannot find module './resolvers/player'.

...
```

**Comment by wittydeveloper** [comment]
Hi @rshkv ,

This an error that I get too, but it's not blocking for the TS compilation, you can take it as warnings.

I'll try to find time to solve this issue soon.

Cheers,
