### ISSUE TITLE
Link in README.md leads to wrong website

### ISSUE THREAD

**Issue by xchange11** [wittydeveloper/spotify-graphql#80]
I think that the URL in 

> API documentation : http://thefrench.house/spotify-graphql/

should actually be 

https://david-dm.org/thefrenchhouse/spotify-graphql

**Comment by wittydeveloper** [comment]
I will publish new online documentation with the `2.0.0` version with a NextJS website and integrated GraphiQL console

**Comment by xchange11** [comment]
> I will publish new online documentation with the 2.0.0 version with a NextJS website and integrated GraphiQL console
👍 

It would nonetheless be good to replace the link or to delete the URL completely. The current URL leads you to a not very trustworthy website.

**Comment by charlypoly** [comment]
> It would nonetheless be good to replace the link or to delete the URL completely. The current URL leads you to a not very trustworthy website.

Done!

**Comment by xchange11** [comment]
Great! Thanks @wittydeveloper
